Repository team-nk/kim-il-jeong-ios, pull requests merged in 2022-11, with the labels that each got.

#43 merge :: header&client추가&map vc수정
  .package.resolved
  iOS/Sources/App/SceneDelegate.swift
  iOS/Sources/Base/BaseTC.swift
  iOS/Sources/Base/BaseVC.swift
  iOS/Sources/Base/TabBarVC.swift
  iOS/Sources/Cell/BirthDayCell.swift
  iOS/Sources/Cell/ScheduleCell.swift
  iOS/Sources/Cell/ToDoTableViewCell.swift
  iOS/Sources/Extension/FloatingPanelController.swift
  iOS/Sources/NetWorking/Client.swift
  iOS/Sources/NetWorking/Header.swift
  iOS/Sources/NetWorking/Service.swift
  iOS/Sources/NetWorking/ServiceType.swift
  iOS/Sources/Scene/Login&SignUp/EmailLogin/EmailLoginVC.swift
  iOS/Sources/Scene/Login&SignUp/EmailLogin/EmailLoginViewModel.swift
  iOS/Sources/Scene/Login&SignUp/Login/LoginVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUp/SignUpVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUp/SignUpViewModel.swift
  iOS/Sources/Scene/Login&SignUp/SignUpCustomAlert/SignUpCustomAlertVC.swift
  iOS/Sources/Scene/Main/UI/MainVC.swift
  iOS/Sources/Scene/Map/DeleteCustomAlert/DeleteCustomAlertVC.swift
  iOS/Sources/Scene/Map/DetailMap/DetailMapVC.swift
  iOS/Sources/Scene/Map/EditPlan/EditPlanVC.swift
  iOS/Sources/Scene/Map/MapView/MapVC.swift
  iOS/Sources/Scene/Map/Modify/ModifyVC.swift
  iOS/Sources/Scene/Map/Modify/ModifyViewModel.swift
  iOS/Sources/Scene/Post/UI/PostListVC.swift
Labels: chore, 기능 추가, 리팩토링

#45 floating panel추가
  ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  iOS/Sources/Scene/Login&SignUp/EmailLoginVC/EmailLoginVC.swift
  iOS/Sources/Scene/Login&SignUp/EmailLoginVC/EmailLoginViewModel.swift
  iOS/Sources/Scene/Login&SignUp/LoginVC/LoginVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUpCustomAlertVC/SignUpCustomAlertVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUpVC/SignUpVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUpVC/SignUpViewModel.swift
  iOS/Sources/Scene/Main/Reactor/MainReactor.swift
  iOS/Sources/Scene/Main/UI/ToDoTableViewCell.swift
  iOS/Sources/Scene/Map/DeleteCustomAlertVC/DeleteCustomAlertVC.swift
  iOS/Sources/Scene/Map/DetailMapVC/DetailMapVC.swift
  iOS/Sources/Scene/Map/EditPlanVC/EditPlanVC.swift
  iOS/Sources/Scene/Map/MapVC/MapVC.swift
  iOS/Sources/Scene/Map/ModifyVC/ModifyVC.swift
  iOS/Sources/Scene/Map/ModifyVC/ModifyViewModel.swift
  iOS/Sources/Scene/Post/Reactor/PostListVCReactor.swift
  iOS/Sources/Scene/Post/UI/BirthDayCell.swift
  iOS/Sources/Scene/Post/UI/NewPostVC.swift
  iOS/Sources/Scene/Post/UI/PostListVC.swift
  iOS/Sources/Scene/Post/UI/ScheduleCell.swift
Labels: 기능 추가, 리팩토링

#47 merge :: mainview modal present
  iOS/Sources/Scene/Main/DetailMainVC/DetailMainVC.swift
  iOS/Sources/Scene/Main/MainEditModifyVC/MainEditModifyVC.swift
  iOS/Sources/Scene/Main/MainModifyVC/MainModifyVC.swift
  iOS/Sources/Scene/Main/MainVC/MainVC.swift
  iOS/Sources/Scene/Main/SearchPositionVC/SearchPositionVC.swift
Labels: 기능 추가

#50 feat :: swiftLint 고치기
  iOS/Sources/Scene/Main/MainEditModifyVC/MainEditModifyVC.swift
  iOS/Sources/Scene/Main/MainModifyVC/MainModifyVC.swift
Labels: 리팩토링

#52 merge :: map 추가
  iOS/Sources/Scene/Main/DetailMainVC/DetailMainVC.swift
Labels: 기능 추가

#54 Feature/post/(#41) post&댓글 조회 UI 제작
  iOS/Resources/Assets.xcassets/NoneProfile.imageset/Contents.json
  iOS/Resources/Assets.xcassets/NoneProfile.imageset/NoneImage 1.svg
  iOS/Resources/Assets.xcassets/NoneProfile.imageset/NoneImage 2.svg
  iOS/Resources/Assets.xcassets/NoneProfile.imageset/NoneImage.svg
  iOS/Resources/Assets.xcassets/PaperPlane.imageset/Contents.json
  iOS/Resources/Assets.xcassets/PaperPlane.imageset/PaperPlane 1.svg
  iOS/Resources/Assets.xcassets/PaperPlane.imageset/PaperPlane 2.svg
  iOS/Resources/Assets.xcassets/PaperPlane.imageset/PaperPlane.svg
  iOS/Resources/Assets.xcassets/Pencil_fill.imageset/Contents.json
  iOS/Resources/Assets.xcassets/Pencil_fill.imageset/Pencil_fill 1.svg
  iOS/Resources/Assets.xcassets/Pencil_fill.imageset/Pencil_fill 2.svg
  iOS/Resources/Assets.xcassets/Pencil_fill.imageset/Pencil_fill.svg
  iOS/Resources/Assets.xcassets/Trash.imageset/Contents.json
  iOS/Resources/Assets.xcassets/Trash.imageset/Trash 1.svg
  iOS/Resources/Assets.xcassets/Trash.imageset/Trash 2.svg
  iOS/Resources/Assets.xcassets/Trash.imageset/Trash.svg
  iOS/Resources/Color.xcassets/GreenColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/YellowColor.colorset/Contents.json
  iOS/Sources/App/SceneDelegate.swift
  iOS/Sources/Base/BaseNC.swift
  iOS/Sources/Extension/CommentListVCTableView.swift
  iOS/Sources/Extension/CommentListVCTextField.swift
  iOS/Sources/Extension/ContentTextView.swift
  iOS/Sources/Extension/PostListVCTableView.swift
  iOS/Sources/Extension/UiTextfiled.swift
  iOS/Sources/Scene/Post/CommentListVC/CommentCell.swift
  iOS/Sources/Scene/Post/CommentListVC/CommentList.swift
  iOS/Sources/Scene/Post/CommentListVC/CommentListVC.swift
  iOS/Sources/Scene/Post/ContentWrappingTableView.swift
  iOS/Sources/Scene/Post/ModelCase/PostDummy.swift
  iOS/Sources/Scene/Post/ModelCase/SettingSection.swift
  iOS/Sources/Scene/Post/NewPostVC/NewPostVC.swift
  iOS/Sources/Scene/Post/PostListVC/BirthDayCell.swift
  iOS/Sources/Scene/Post/PostListVC/PostDummy.swift
  iOS/Sources/Scene/Post/PostListVC/PostListVC.swift
  iOS/Sources/Scene/Post/PostListVC/ScheduleCell.swift
  iOS/Sources/Scene/Post/PostVC/PostVC.swift
Labels: 기능 추가

#56 login&signup api연동및 비동기 처리
  iOS/Sources/NetWorking/Client.swift
  iOS/Sources/NetWorking/MoyaPlugin/MoyaLoggerPlugin.swift
  iOS/Sources/NetWorking/Service.swift
  iOS/Sources/Scene/Login&SignUp/EmailLogin/EmailLoginVC.swift
  iOS/Sources/Scene/Login&SignUp/EmailLogin/EmailLoginViewModel.swift
  iOS/Sources/Scene/Login&SignUp/SignUp/SignUpVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUp/SignUpViewModel.swift
  iOS/Sources/Scene/Main/MainVC/MainVC.swift
  iOS/Sources/Scene/Map/MapView/MapVC.swift
  iOS/Sources/Scene/Model/TokenModel.swift
Labels: 기능 추가, 리팩토링

#59 api&code 리펙토링
  iOS/Sources/Base/TabBarVC.swift
  iOS/Sources/Cell/BirthDayCell.swift
  iOS/Sources/Cell/CommentCell.swift
  iOS/Sources/Cell/ScheduleCell.swift
  iOS/Sources/NetWorking/Service.swift
  iOS/Sources/Scene/Login&SignUp/SignUp/SignUpVC.swift
  iOS/Sources/Scene/Main/MainVC/MainVC.swift
  iOS/Sources/Scene/Model/TokenModel.swift
Labels: chore, 리팩토링

#60 feat :: (#57) my page UI 퍼블리싱
  iOS/Resources/Assets.xcassets/NextButtonImage.imageset/Contents.json
  iOS/Resources/Assets.xcassets/NextButtonImage.imageset/NextButtonImage 1.svg
  iOS/Resources/Assets.xcassets/NextButtonImage.imageset/NextButtonImage 2.svg
  iOS/Resources/Assets.xcassets/NextButtonImage.imageset/NextButtonImage.svg
  iOS/Sources/Base/TabBarVC.swift
  iOS/Sources/Extension/MyPageVCTableView.swift
  iOS/Sources/Extension/PostListVCTableView.swift
  iOS/Sources/Extension/UiTextfiled.swift
  iOS/Sources/Scene/MyPage/LogOutCustomAlertVC.swift
  iOS/Sources/Scene/MyPage/MyBirthSheetVC.swift
  iOS/Sources/Scene/MyPage/MyEditVC.swift
  iOS/Sources/Scene/MyPage/MyPageMenuCell.swift
  iOS/Sources/Scene/MyPage/MyPageVC.swift
  iOS/Sources/Scene/MyPage/MyPostVC.swift
  iOS/Sources/Scene/MyPage/PasswordEditVC.swift
  iOS/Sources/Scene/MyPage/PasswordEditViewModel.swift
  iOS/Sources/Scene/Post/CommentListVC/CommentListVC.swift
Labels: 기능 추가
