Repository team-nk/kim-il-jeong-ios, pull requests merged in 2022-09, with the labels that each got.

#9 feat :: README file 수정
  README.md
Labels: Docs

#10 Test/(#7) readme파일변경
  README.md
Labels: Docs

#12 delete :: README 내용 없에기
  README.md
Labels: chore

#15 merge :: (#14) 파일 구조 다시 만들기
  Service/Project.swift
  Workspace.swift
  iOS/Sources/App/SceneDelegate.swift
  iOS/Sources/Flow/AppFlow.swift
  iOS/Sources/Flow/Flows/MainFlow.swift
  iOS/Sources/Scene/Login/Reactor/LoginReactor.swift
  iOS/Sources/Scene/Login/UI/LoginVC.swift
Labels: chore

#16 merge :: (#14) 파일 구조 다시 만들기 2
  Service/Sources/Service.swift
Labels: 버그

#20 project :: (#19) add color assets
  iOS/Resources/Color.xcassets/BackGroundColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/BackGroundColor2.colorset/Contents.json
  iOS/Resources/Color.xcassets/ChapterDeactivationColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/DarkmodeBackGround.colorset/Contents.json
  iOS/Resources/Color.xcassets/DarkmodeDescriptionTextColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/DarkmodeTextColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/Description.colorset/Contents.json
  iOS/Resources/Color.xcassets/ErrorColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/StatusBarTextColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/StrongExplanation.colorset/Contents.json
  iOS/Resources/Color.xcassets/Surface2.colorset/Contents.json
  iOS/Resources/Color.xcassets/SurfaceColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/TextColor.colorset/Contents.json
  iOS/Resources/Color.xcassets/TextfieldDeactivationColor.colorset/Contents.json
Labels: 프로젝트 설정
