Repository team-nk/kim-il-jeong-ios, pull requests merged in 2023-01, with the labels that each got.

#65 merge :: MapView API 연동
  iOS/Model/MyMapSchedulesToken.swift
  iOS/Model/MySchedulesToken.swift
  iOS/Model/TokenModel.swift
  iOS/Sources/Base/TabBarVC.swift
  iOS/Sources/NetWorking/Client.swift
  iOS/Sources/NetWorking/Header.swift
  iOS/Sources/NetWorking/Service.swift
  iOS/Sources/Scene/Cell/BirthDayCell.swift
  iOS/Sources/Scene/Cell/CommentCell.swift
  iOS/Sources/Scene/Cell/DetailLocationTableViewCell.swift
  iOS/Sources/Scene/Cell/ScheduleCell.swift
  iOS/Sources/Scene/Cell/ToDoTableViewCell.swift
  iOS/Sources/Scene/Login&SignUp/SignUp/SignUpVC.swift
  iOS/Sources/Scene/Main/MainVC/MainVC.swift
  iOS/Sources/Scene/Main/MainVC/MainViewModel.swift
  iOS/Sources/Scene/Map/DetailMap/DetailMapVC.swift
  iOS/Sources/Scene/Map/DetailMap/DetailMapViewModel.swift
  iOS/Sources/Scene/Map/MapView/MapVC.swift
Labels: 기능 추가, 리팩토링

#67 merge :: Model 추가
  iOS/Sources/Model/MyMapSchedulesModel.swift
  iOS/Sources/Model/MySchedulesModel.swift
  iOS/Sources/NetWorking/Service.swift
Labels: 기능 추가

#68 feat :: (#63) Post Page API 연동
  iOS/Sources/Extension/CommentListVCTableView.swift
  iOS/Sources/Extension/PostListVCTableView.swift
  iOS/Sources/Model/CommentModel.swift
  iOS/Sources/Model/PostModel.swift
  iOS/Sources/NetWorking/Client.swift
  iOS/Sources/NetWorking/Service.swift
  iOS/Sources/Scene/Map/Modify/ModifyVC.swift
  iOS/Sources/Scene/MyPage/LogOutAlertVC/LogOutCustomAlertVC.swift
  iOS/Sources/Scene/MyPage/MyPageVC/MyPageVC.swift
  iOS/Sources/Scene/MyPage/MyPostVC/MyPostVC.swift
  iOS/Sources/Scene/Post/CommentListVC/CommentList.swift
  iOS/Sources/Scene/Post/CommentListVC/CommentListVC.swift
  iOS/Sources/Scene/Post/CommentListVC/CommentListVM.swift
  iOS/Sources/Scene/Post/CommentListVC/NewCommentVM.swift
  iOS/Sources/Scene/Post/NewPostVC/NewPostVC.swift
  iOS/Sources/Scene/Post/PostListVC/PostDummy.swift
  iOS/Sources/Scene/Post/PostListVC/PostListVC.swift
  iOS/Sources/Scene/Post/PostListVC/PostListVM.swift
  iOS/Sources/Scene/Post/PostVC/PostVC.swift
Labels: 기능 추가, 리팩토링

#70 feat :: (#69) Post Page 코드 리팩토링
  .package.resolved
  iOS/Sources/NetWorking/Client.swift
  iOS/Sources/Scene/MyPage/MyPostVC/MyPostVC.swift
  iOS/Sources/Scene/Post/PostListVC/PostListVC.swift
Labels: 리팩토링

#75 feat :: finish map vc
  iOS/Sources/Extension/Date.swift
  iOS/Sources/Extension/String.swift
  iOS/Sources/Extension/UIButton.swift
  iOS/Sources/Extension/UILabel.swift
  iOS/Sources/Extension/UiTextfiled.swift
  iOS/Sources/Model/LocationModel.swift
  iOS/Sources/Model/MySchedulesModel.swift
  iOS/Sources/Scene/Cell/ToDoTableViewCell.swift
  iOS/Sources/Scene/KakaoZipCode/KaKaoZipCodeVC.swift
  iOS/Sources/Scene/Login&SignUp/Login/LoginVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUp/SignUpVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUpCustomAlert/SignUpCustomAlertVC.swift
  iOS/Sources/Scene/Main/DetailMainVC/DetailMainVC.swift
  iOS/Sources/Scene/Main/MainEditModifyVC/MainEditModifyVC.swift
  iOS/Sources/Scene/Main/MainEditModifyVC/MainEditModifyViewModel.swift
  iOS/Sources/Scene/Main/MainModifyVC/MainModifyVC.swift
  iOS/Sources/Scene/Main/MainModifyVC/MainModifyViewModel.swift
  iOS/Sources/Scene/Main/MainVC/MainVC.swift
  iOS/Sources/Scene/Map/EditPlan/EditPlanVC.swift
  iOS/Sources/Scene/Map/MapView/CustomPointAnnotation.swift
  iOS/Sources/Scene/Map/MapView/MapVC.swift
  iOS/Sources/Scene/Map/Modify/ModifyVC.swift
  iOS/Sources/Scene/Map/Modify/ModifyViewModel.swift
Labels: chore, 기능 추가, 리팩토링

#77 refactor :: 코드 리펙토링
  .package.resolved
  iOS/Sources/Scene/Login&SignUp/EmailLogin/EmailLoginVC.swift
  iOS/Sources/Scene/Login&SignUp/SignUp/SignUpVC.swift
  iOS/Sources/Scene/Main/MainModifyVC/MainModifyVC.swift
  iOS/Sources/Scene/Map/DetailMap/DetailMapVC.swift
  iOS/Sources/Scene/Map/EditPlan/EditPlanVC.swift
  iOS/Sources/Scene/Map/Modify/ModifyVC.swift
Labels: chore, 리팩토링

#78 refactor :: text 수정
  iOS/Sources/Scene/Map/Modify/ModifyVC.swift
Labels: chore, 리팩토링
